### ISSUE TITLE
Error: Could not use git, please make sure it is installed and available in your PATH.

### ISSUE THREAD

**Issue by hoaanhmine** [Realmzer/PsychSwitcher#2]
![Screenshot 2024-08-23 223506](https://github.com/user-attachments/assets/b54684a9-a845-4ffb-900c-9ac5adc364b5)
Error: Could not use git, please make sure it is installed and available in your PATH.

C:\Users\PC\Desktop\relax\fnf\0.7.3\mods>haxelib git flxanimate https://github.com/ShadowMario/flxanimate dev

A new version (4.1.0) of haxelib is available.
Do `haxelib --global update haxelib` to get the latest version.

Error: Could not use git, please make sure it is installed and available in your PATH.

C:\Users\PC\Desktop\relax\fnf\0.7.3\mods>haxelib git linc_luajit https://github.com/superpowers04/linc_luajit

A new version (4.1.0) of haxelib is available.
Do `haxelib --global update haxelib` to get the latest version.

Error: Could not use git, please make sure it is installed and available in your PATH.

C:\Users\PC\Desktop\relax\fnf\0.7.3\mods>haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc

A new version (4.1.0) of haxelib is available.
Do `haxelib --global update haxelib` to get the latest version.

Error: Could not use git, please make sure it is installed and available in your PATH.

C:\Users\PC\Desktop\relax\fnf\0.7.3\mods>echo Complete!
Complete!

C:\Users\PC\Desktop\relax\fnf\0.7.3\mods>pause
Press any key to continue . . .

**Comment by Realmzer** [comment]
try using git in the latest commit it should be working now
